# Generated by Django 2.2.4 on 2020-07-19 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('origem', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField()),
                ('level', models.CharField(choices=[('A', 'All'), ('D', 'Debug'), ('I', 'Info'), ('W', 'Warning'), ('E', 'Error'), ('F', 'Fatal'), ('O', 'Off'), ('T', 'Trace')], max_length=1)),
                ('tipo', models.CharField(choices=[('P', 'Produção'), ('H', 'Homologação'), ('D', 'Dev')], max_length=1)),
                ('eventos', models.BigIntegerField()),
                ('detalhes', models.CharField(blank=True, max_length=400, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
