# Generated by Django 2.2.4 on 2020-07-06 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200706_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='eventos',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_registro',
            field=models.DateTimeField(),
        ),
    ]
