# Generated by Django 2.2.4 on 2020-07-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200706_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='eventos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
