# Generated by Django 2.2.4 on 2020-07-07 19:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20200706_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='Log',
        ),
    ]
