# Generated by Django 2.2.4 on 2020-07-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200707_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='prioridade',
            new_name='level',
        ),
        migrations.AddField(
            model_name='log',
            name='detalhes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
